# Generated by Django 6.0.6 on 2026-06-25 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0002_materia_normabncc'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objeto_conhecimento', models.TextField(blank=True)),
                ('habilidades_bncc', models.TextField(blank=True)),
                ('objetivos_especificos', models.TextField(blank=True)),
                ('recursos', models.TextField(blank=True)),
                ('avaliacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('dia_letivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos', to='escola.dialetivo')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos', to='escola.materia')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos', to='escola.turma')),
            ],
            options={
                'unique_together': {('turma', 'materia', 'dia_letivo')},
            },
        ),
    ]
