# Generated by Django 6.0.6 on 2026-06-25 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0003_planoaula'),
    ]

    operations = [
        migrations.CreateModel(
            name='AulaPlanejamentoGeral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema_aula', models.CharField(blank=True, max_length=255)),
                ('dia_letivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas_gerais', to='escola.dialetivo')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas_gerais', to='escola.materia')),
                ('normas', models.ManyToManyField(blank=True, to='escola.normabncc')),
                ('trimestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas_gerais', to='escola.trimestre')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas_gerais', to='escola.turma')),
            ],
            options={
                'ordering': ['dia_letivo__data'],
                'unique_together': {('turma', 'materia', 'dia_letivo')},
            },
        ),
    ]
