# Generated by Django 6.0.6 on 2026-06-25 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0004_aulaplanejamentogeral'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnoLetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(unique=True)),
                ('corrente', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='dialetivo',
            name='ano_letivo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dias', to='escola.anoletivo'),
        ),
    ]
