# Generated by Django 6.0.6 on 2026-06-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0005_anoletivo_dialetivo_ano_letivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='aulaplanejamentogeral',
            name='sugestoes_atividades',
            field=models.TextField(blank=True),
        ),
    ]
