# Generated by Django 6.0.6 on 2026-06-26 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0006_aulaplanejamentogeral_sugestoes_atividades'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistribuicaoMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequencia', models.CharField(choices=[('TODOS', 'Todos os dias'), ('FIXO', 'Dia Fixo'), ('RODIZIO', 'Rodízio')], default='TODOS', max_length=10)),
                ('dia_semana', models.IntegerField(blank=True, choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira')], null=True)),
                ('ordem_rodizio', models.IntegerField(default=1, help_text='Se for rodízio, defina a ordem (1, 2, 3...) entre as matérias que dividem o mesmo dia.')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribuicoes', to='escola.materia')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribuicoes', to='escola.turma')),
            ],
            options={
                'verbose_name': 'Distribuição de Matéria',
                'verbose_name_plural': 'Distribuições de Matérias',
                'unique_together': {('turma', 'materia')},
            },
        ),
    ]
