# Generated by Django 6.0.6 on 2026-06-27 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0007_distribuicaomateria'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtividadeDisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dinamica', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escola.materia')),
            ],
        ),
        migrations.CreateModel(
            name='ArquivoAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive_id', models.CharField(blank=True, max_length=255, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('nome_arquivo', models.CharField(max_length=255)),
                ('texto_extraido', models.TextField(blank=True)),
                ('resumo_ia', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='escola.atividadedisciplina')),
            ],
        ),
        migrations.CreateModel(
            name='PlanoDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objeto_conhecimento', models.TextField(blank=True)),
                ('habilidades_bncc', models.TextField(blank=True)),
                ('objetivos_especificos', models.TextField(blank=True)),
                ('recursos', models.TextField(blank=True)),
                ('avaliacao', models.TextField(blank=True)),
                ('componentes_curriculares', models.TextField(blank=True)),
                ('conteudo_ministrado', models.TextField(blank=True)),
                ('finalizado', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('dia_letivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos_dia', to='escola.dialetivo')),
                ('trimestre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='escola.trimestre')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos_dia', to='escola.turma')),
            ],
            options={
                'ordering': ['dia_letivo__data'],
                'unique_together': {('turma', 'dia_letivo')},
            },
        ),
        migrations.AddField(
            model_name='atividadedisciplina',
            name='plano_dia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='escola.planodia'),
        ),
    ]
