# Generated by Django 6.0.6 on 2026-06-28 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0008_atividadedisciplina_arquivoatividade_planodia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAulaTurma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presenca_lancada', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('dia_letivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_aula', to='escola.dialetivo')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_aula', to='escola.turma')),
            ],
            options={
                'verbose_name': 'Registro de Aula da Turma',
                'verbose_name_plural': 'Registros de Aulas das Turmas',
                'unique_together': {('turma', 'dia_letivo')},
            },
        ),
        migrations.CreateModel(
            name='FrequenciaAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presente', models.BooleanField(default=True)),
                ('justificativa', models.TextField(blank=True, help_text='Obrigatório se presente=False')),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequencias', to='escola.aluno')),
                ('registro_aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequencias', to='escola.registroaulaturma')),
            ],
            options={
                'verbose_name': 'Frequência do Aluno',
                'verbose_name_plural': 'Frequências dos Alunos',
                'unique_together': {('registro_aula', 'aluno')},
            },
        ),
    ]
