# Generated by Django 6.0.6 on 2026-06-28 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0009_registroaulaturma_frequenciaaluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroaulaturma',
            name='motivo_cancelamento',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='registroaulaturma',
            name='observacoes_gerais',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='registroaulaturma',
            name='status',
            field=models.CharField(choices=[('P', 'Pendente'), ('M', 'Ministrada'), ('C', 'Cancelada')], default='P', max_length=1),
        ),
        migrations.CreateModel(
            name='DocumentoPlanoAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive_id', models.CharField(max_length=255)),
                ('link_pdf', models.URLField()),
                ('nome_arquivo', models.CharField(max_length=255)),
                ('gerado_em', models.DateTimeField(auto_now_add=True)),
                ('plano_dia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documento_pdf', to='escola.planodia')),
            ],
        ),
        migrations.CreateModel(
            name='RelatorioTrimestralAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versao', models.IntegerField(default=1)),
                ('visao_geral', models.TextField()),
                ('linguagem', models.TextField()),
                ('matematica', models.TextField()),
                ('ciencias', models.TextField()),
                ('conclusao', models.TextField()),
                ('drive_id', models.CharField(blank=True, max_length=255, null=True)),
                ('link_pdf', models.URLField(blank=True, null=True)),
                ('gerado_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios', to='escola.aluno')),
                ('trimestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escola.trimestre')),
            ],
            options={
                'ordering': ['-versao'],
                'unique_together': {('aluno', 'trimestre', 'versao')},
            },
        ),
    ]
